apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marquez-postgres-pvc
  namespace: openlineage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marquez-postgres
  namespace: openlineage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marquez-postgres
  template:
    metadata:
      labels:
        app: marquez-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: marquez
            - name: POSTGRES_PASSWORD
              value: marquez
            - name: POSTGRES_DB
              value: marquez
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: marquez-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: marquez-postgres
  namespace: openlineage
spec:
  selector:
    app: marquez-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
