version: "3"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-metastore
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    image: starburstdata/hive:3.1.3-e.14-arm64
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_URI: thrift://0.0.0.0:9083
      HIVE_METASTORE_JDBC_URL: jdbc:mysql://mysql:3306/metastore?createDatabaseIfNotExist=true
      HIVE_METASTORE_DRIVER: com.mysql.jdbc.Driver
      HIVE_METASTORE_USER: root
      HIVE_METASTORE_PASSWORD: root
      S3_ENDPOINT: dummy
      S3_ACCESS_KEY: dummy
      S3_SECRET_KEY: dummy
      S3_PATH_STYLE_ACCESS: "true"
      REGION: dummy
      #HIVE_METASTORE_DRIVER: org.postgresql.Driver
      #HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      #HIVE_METASTORE_USER: hive
      #HIVE_METASTORE_PASSWORD: hive
      #HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      #S3_ENDPOINT: http://minio:9000
      #S3_ACCESS_KEY: minio
      #S3_SECRET_KEY: minio123
      #S3_PATH_STYLE_ACCESS: "true"
      #REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USERS_IN_ADMIN_ROLE: "admin"
    ports:
      - "9083:9083"
    volumes:
      - /Users/dave/dev/RETrend/tmp/raw/iceberg:/Users/dave/dev/RETrend/tmp/raw/iceberg
    depends_on:
      mysql:
        condition: service_healthy

  trino:
    image: trinodb/trino:441
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - /Users/dave/dev/RETrend/tmp/raw/iceberg:/Users/dave/dev/RETrend/tmp/raw/iceberg

  superset:
    image: dave126/superset_v5.0.0_trino:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
      - SUPERSET_LOAD_EXAMPLES=no
      - FLASK_APP=superset
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/superset_home/superset.db
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
      "

volumes:
  superset_home: