apiVersion: v1
kind: Secret
metadata:
  name: airflow-superset-auth
  namespace: airflow
type: Opaque
stringData:
  SUPERSET_BASE_URL: "http://172.30.1.40:8088"
  SUPERSET_USERNAME: ""
  SUPERSET_PASSWORD: ""
